# coding: utf-8

"""
    Pig Game API

    API for playing the classic dice game Pig.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.game_management_api import router as GameManagementApiRouter
from openapi_server.apis.gameplay_api import router as GameplayApiRouter

app = FastAPI(
    title="Pig Game API",
    description="API for playing the classic dice game Pig.",
    version="1.0.0",
)

app.include_router(GameManagementApiRouter)
app.include_router(GameplayApiRouter)
